version: "3.4"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'foodnas'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/config:/docker-entrypoint-initdb.d
      - ./db/backup:/backup